### ISSUE TITLE
Чекбокс - отступы

### ISSUE THREAD

**Issue by jigius** [jigius/tpl-verhtorm#11]
@ChesnokovAlexander 

Убрать отступы, которые появляются, если чекбокс "зачекан".

![checkbox-issue](https://github.com/jigius/tpl-verhtorm/assets/24520522/17be5983-0be8-428c-b52d-11d9a255415e)

**Comment by ChesnokovAlexander** [comment]
Сделано

**Comment by jigius** [comment]
@ChesnokovAlexander 

Если поставить и снять галочку, то пропадает бордер у контрола

![check-issue2](https://github.com/jigius/tpl-verhtorm/assets/24520522/1286bef4-3cde-47e2-a173-37ed353e18b6)

**Comment by ChesnokovAlexander** [comment]
Исправил

**Comment by jigius** [comment]
норм
