### ISSUE TITLE
Моб.версия / список сортировки и кнопка показа/скрытия фильтра -требуется изменить стили 

### ISSUE THREAD

**Issue by jigius** [jigius/tpl-verhtorm#12]
@ChesnokovAlexander 

Файлы:

- `src/partials/category/filter-mob.html`
- `src/partials/category/sorting-cntr-mob.html`

1. Сделать высоту `.select` 32px
2. Стилизовать  `.select__content`
3. Сделать высоту `.btn.catalog-btn` 32px
4. Выравнять элементы `.select` и `.btn.catalog-btn`  относительно друг друга по вертикали

**Comment by ChesnokovAlexander** [comment]
Сделано

**Comment by jigius** [comment]
норм
