### ISSUE TITLE
Сверстанная структура фильтров не та, что указана в требованиях ТЗ

### ISSUE THREAD

**Issue by jigius** [jigius/tpl-verhtorm#2]
@Alexander96196 
В требованиях указано какая ожидается структура фильтра -  см. Техническое задание / Ожидаемый результат ([п3](https://github.com/jigius/tpl-verhtorm#%D0%BE%D0%B6%D0%B8%D0%B4%D0%B0%D0%B5%D0%BC%D1%8B%D0%B9-%D1%80%D0%B5%D0%B7%D1%83%D0%BB%D1%8C%D1%82%D0%B0%D1%82)) :(

Я посмотрел твой вариант его структуры - я смогу ее взять в работу, поэтому переделывать, согласно ТЗ,  не надо.

Для того, чтобы мне взять в работу, сверстанную тобою структуру фильтра, мне нужно, чтобы если у  элемента `ul.panel-body`  указать правило `overflow: hidden;`, то это бы не приводило к обрезанию по левой границе у дочерних li-элементов.

**Comment by ChesnokovAlexander** [comment]
Понял, щас поправлю

**Comment by ChesnokovAlexander** [comment]
Исправлено

**Comment by jigius** [comment]
норм.
