### ISSUE TITLE
Контролы вверху у моб.фильтра не такие как описаны в референсах ТЗ

### ISSUE THREAD

**Issue by jigius** [jigius/tpl-verhtorm#3]
@Alexander96196 
Смотри Техническое задание / Референсы (п2) - картинки.

Картинка 1 - скрытый фильтр
Картинка 2 - раскрытый фильтр

Проблемы:
1. Нет список-контролла, используемый для сортировки.
2. Контролл скрыть/показать фильтр - не такой как на референсах в ТЗ.

**Comment by ChesnokovAlexander** [comment]
Сделано

**Comment by jigius** [comment]
Норм, но есть замечание по проблеме п1. Опишу отдельно.
