### ISSUE TITLE
Моб. фильтр - контрол свернуть/развернуть

### ISSUE THREAD

**Issue by jigius** [jigius/tpl-verhtorm#5]
@Alexander96196 

Мне нужно знать - на какой элемент фильтра мне нужно указать какой класс(классы), чтобы выставить его состояние (свернутый/развернутый).

**Comment by ChesnokovAlexander** [comment]
catalog-btn--show показывает раскрытый фильтр
catalog-btn закрытый фильтр
При клике на кнопку фильтра, нужно на .tf-filter__mobile вешать  display: none и убирать catalog-btn--show, а при открытие все наоборот.

**Comment by jigius** [comment]
норм.
