### ISSUE TITLE
Список-контролл для сортировки у моб. фильтра

### ISSUE THREAD

**Issue by jigius** [jigius/tpl-verhtorm#8]
@Alexander96196 

Ожидается поведение такое же, как на ТЗ / Референсы (п1)

Проблемы:
1. Не раскрывается список при тапе/клике на участок контролла  на которой размещена стрелка вниз.
2.  При раскрытии списка никак не подсвечивается текущий элемент.
3. При раскрытии списка, стрелка на контролле остается прежней - направлена вниз.

**Comment by ChesnokovAlexander** [comment]
Поправил.
Для поворота стрелки нужно добавить классу panel-title active.

**Comment by jigius** [comment]
Нет, не пойдет :( Проблема N1 по-прежнему не решена и поскольку использован  стандартный селект - контролировать его состояние для перевората стрелки это лишнее.

Сделай так:
1. Убери стрелку-нашлепку, расположенного поверх селекта, вовсе.
2. Включи показ стандартной для селекта - стрелка вниз (всегда). Для этого нужно выключить свойство `apperance` у селекта.
3. У текущего, выбранного пункта селекта: `background-color: #48cfad` и `color: #fff `

**Comment by ChesnokovAlexander** [comment]
1,2 пункт поправил, с 3 пунктом проблема у дефолтного option без js не убрать синие выделение

**Comment by jigius** [comment]
> с 3 пунктом проблема у дефолтного option без js не убрать синие выделение

Можешь мне здесь привести js-код для этого или ссылку дать на то как это сделать?

**Comment by ChesnokovAlexander** [comment]
HTML и CSS написан, JS этот вставить и все будет работать.

<code>const selectSingle = document.querySelector('.select');
const selectSingle_title = selectSingle.querySelector('.select__title');
const selectSingle_labels = selectSingle.querySelectorAll('.select__label');
selectSingle_title.addEventListener('click', () => {
  if ('active' === selectSingle.getAttribute('data-state')) {
    selectSingle.setAttribute('data-state', '');
  } else {
    selectSingle.setAttribute('data-state', 'active');
  }
});
for (let i = 0; i < selectSingle_labels.length; i++) {
  selectSingle_labels[i].addEventListener('click', (evt) => {
    selectSingle_title.textContent = evt.target.textContent;
    selectSingle.setAttribute('data-state', '');
  });
}</code>

**Comment by jigius** [comment]
норм.
