### ISSUE TITLE
Контролы сортировки (кнопки)  у десктопной версии

### ISSUE THREAD

**Issue by jigius** [jigius/tpl-verhtorm#9]
@Alexander96196 

Ожидается поведение такое же, как на ТЗ / Референсы (п1,п3)

Проблемы:

1. Добавить подсветку для hover у кнопок -  смотри ТЗ / Референсы (п1)
2. Сделать подсветку кнопки, указывающей на текущее состояние выбора - смотри ТЗ / Референсы (п1)

**Comment by ChesnokovAlexander** [comment]
Hover был сделан, добавил активное состояние кнопки. Необходимо классу sorting__item добавить active.

**Comment by jigius** [comment]
> Hover был сделан

Можешь его стиль поправить, чтобы он был такой же как не референсном сайте - подсвечивал только границы?

**Comment by ChesnokovAlexander** [comment]
Сделано

**Comment by jigius** [comment]
норм

**Comment by jigius** [comment]
норм
